/**
 * App-owned tables (NOT part of mims_app, NOT regenerated by `drizzle-kit pull`).
 * Keep these out of schema.ts so a future `npm run db:pull` doesn't clobber them.
 */
import { pgTable, uuid, text, boolean, timestamp, index, foreignKey, check } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { negocios } from "./schema";

export const users = pgTable("users", {
  id: uuid().defaultRandom().primaryKey().notNull(),
  negocioId: uuid("negocio_id").notNull(),
  email: text().notNull(),
  passwordHash: text("password_hash").notNull(),
  nombre: text(),
  role: text().default("owner").notNull(),
  activo: boolean().default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).defaultNow().notNull(),
}, (table) => [
  index("idx_users_negocio").using("btree", table.negocioId).where(sql`(activo = true)`),
  foreignKey({
    columns: [table.negocioId],
    foreignColumns: [negocios.id],
    name: "users_negocio_id_fkey",
  }).onDelete("cascade"),
  check("users_role_check", sql`role = ANY (ARRAY['owner'::text, 'staff'::text])`),
]);

export type User = typeof users.$inferSelect;
