-- Real production logins (2 negocios). Passwords are bcrypt hashes generated by the owner;
-- plaintext is NOT stored anywhere. negocio_id resolved from the real negocios.id by slug.
--
-- Requires the `users` table to exist first (db/users.sql).
-- Idempotent: ON CONFLICT on the lower(email) unique index does nothing, so it can be re-run.
-- Only inserts if the negocio slug exists (SELECT returns 0 rows otherwise).

INSERT INTO users (negocio_id, email, password_hash, role)
SELECT id, 'tasqueta@mims.studio', '$2b$10$Kv5h5oKye4pOJlGWxdbgtuDYnO923tnEYxYQruLDXqQ1B8j1aiCJy', 'owner'
FROM negocios WHERE slug = 'la-tasqueta-llivia'
ON CONFLICT (lower(email)) DO NOTHING;

INSERT INTO users (negocio_id, email, password_hash, role)
SELECT id, 'dentos@mims.studio', '$2b$10$dqnrCmN2sqQfgrkmVso4veet/ywoc3Yjs4OgtOLThmnQwIxRFiIAG', 'owner'
FROM negocios WHERE slug = 'clinica-dentos'
ON CONFLICT (lower(email)) DO NOTHING;
